services:
  # 開発環境
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:kaisei_password@db-dev:5432/kaisei_dev
    depends_on:
      - db-dev
    command: npm run dev

  # データベース（開発用）
  db-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kaisei_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kaisei_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  next_cache: 
