services:
  # 開発環境
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    command: ["sh", "/app/scripts/start-dev.sh"]

  # データベース（開発用）- ローカルPostgreSQL（Neon接続に問題がある場合のフォールバック）
  db-dev:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kaisei_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kaisei_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  next_cache: 
